name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.9.0

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools wasm-experimental

      - name: Install DotNetCompress
        run: dotnet tool install --global DotNetCompress --version 1.0.0-preview.5 --no-cache

      - name: Publish .NET Project
        run: dotnet publish LogicalTable/LogicalTable.Browser/LogicalTable.Browser.fsproj -c Release -o release --nologo

      - name: Brotli Compress Output (dll)
        run: DotNetCompress -d LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/managed -p '*.dll' --format br --threads 4

      - name: Brotli Compress Output (js)
        run: DotNetCompress -d LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/ -p '*.js' --format br --threads 4

      - name: Brotli Compress Output (wasm)
        run: DotNetCompress -d LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/ -p '*.wasm' --format br --threads 4

      - name: GZip Compress Output (dll)
        run: DotNetCompress -d LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/managed -p '*.dll' --format gz --threads 4

      - name: GZip Compress Output (js)
        run: DotNetCompress -d LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/ -p '*.js' --format gz --threads 4

      - name: GZip Compress Output (wasm)
        run: DotNetCompress -d LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/ -p '*.wasm' --format gz --threads 4

      - name: Change base-tag in index.html from / to XamlPlayground
        run: sed -i 's/<base href="\/" \/>/<base href="\/XamlPlayground\/" \/>/g' LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/index.html

      - name: copy index.html to 404.html
        run: cp LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/index.html LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/404.html

      - name: Add .nojekyll file
        run: touch LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: LogicalTable/LogicalTable.Browser/bin/Release/net7.0/browser-wasm/AppBundle